# -*- coding: utf-8 -*-
"""Task_02/Py_calc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18huKIQuM9Bc9ChYMjxZAJgzHnnrJpd8I
"""

operator = input('''Please type in the math operation you would like to complete:\n+ for addition\n- for subtraction\n* for multiplication\n/ for division:\n ''')

num_1=float(input("Enter first number: "))
num_2=float(input("Enter second number: "))

if operator == '+':
  print(f"Addition of two number is: {num_1 + num_2}")

elif operator == '-':
  print(f"Subtraction of two number is: {num_1 - num_2}")

elif operator == '*':
  print(f"Multiplication of two number is: {num_1 * num_2}")

elif operator == '/':
  print(f"Division of two number is: {num_1 / num_2}")
else:
  print("Invalid input")

